### ISSUE TITLE
.transport.LowerTransportLayer.sendBlockAck crash

### ISSUE THREAD

**Issue by WangManAndroid** [NordicSemiconductor/Android-nRF-Mesh-Library#108]
`12-13 10:43:30.429 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: discoverServices() - device: 98:12:88:77:00:15
12-13 10:43:30.429 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetService() - Device=98:12:88:77:00:15 UUID=00001800-0000-1000-8000-00805f9b34fb
12-13 10:43:30.429 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetService() - Device=98:12:88:77:00:15 UUID=00001801-0000-1000-8000-00805f9b34fb
12-13 10:43:30.429 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetService() - Device=98:12:88:77:00:15 UUID=00001828-0000-1000-8000-00805f9b34fb
12-13 10:43:30.429 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002a00-0000-1000-8000-00805f9b34fb
12-13 10:43:30.439 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002a01-0000-1000-8000-00805f9b34fb
12-13 10:43:30.439 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002a04-0000-1000-8000-00805f9b34fb
12-13 10:43:30.439 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002a05-0000-1000-8000-00805f9b34fb
12-13 10:43:30.449 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002add-0000-1000-8000-00805f9b34fb
12-13 10:43:30.449 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetCharacteristic() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:30.449 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetDescriptor() - Device=98:12:88:77:00:15 UUID=00002902-0000-1000-8000-00805f9b34fb
12-13 10:43:30.459 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onGetDescriptor() - Device=98:12:88:77:00:15 UUID=00002902-0000-1000-8000-00805f9b34fb
12-13 10:43:30.459 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onSearchComplete() = Device=98:12:88:77:00:15 Status=0
12-13 10:43:30.459 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ Thread: main
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ MeshProvisionerActivity$1.onChanged  (MeshProvisionerActivity.java:193)
    │    Debuger.d  (Debuger.java:16)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ Initializing…
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
12-13 10:43:30.469 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: setCharacteristicNotification() - uuid: 00002ade-0000-1000-8000-00805f9b34fb enable: true
12-13 10:43:30.469 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeDescriptor() - uuid: 00002902-0000-1000-8000-00805f9b34fb
12-13 10:43:30.539 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onDescriptorWrite() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:30.539 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/PRETTY_LOGGER: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    │ Thread: Binder_1
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
    │ MeshService.onDeviceReady  (MeshService.java:405)
    │    Debuger.d  (Debuger.java:16)
    ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
12-13 10:43:30.549 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/PRETTY_LOGGER: │ 98:12:88:77:00:15
    └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
12-13 10:43:32.549 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/MeshTransport: Src address: 07FF
    Dst address: 002B
    Key: C3BE94232FFFB189256CC19760C5A4A0
    akf: 0
    aid: 0
    aszmic: 0
    Sequence number: 123
    Access message opcode: 32776
    Access message parameters: FF
12-13 10:43:32.549 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/AccessLayer: Created Access PDU 8008FF
12-13 10:43:32.549 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/UpperTransportLayer: Device nonce: 020000007B07FF002B00000000
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/UpperTransportLayer: Encrypted upper transport pdu: 7174AC29C3B4C1
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: Unsegmented Lower transport access PDU 007174AC29C3B4C1
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Encryption key: 09D98362AFD9980568560D7ABB90472E
    Privacy key: F9CA93F9110E9AD5EF741B35DF2C35F4
    Sequence Number: 00007B
    Network nonce: 006400007B07FF000000000000
    Encrypted Network payload: 86FCB04510E4CDCBA38C2B8C6A44
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataGet: Sending composition data get
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0x400C2793473B679886FCB04510E4CDCBA38C2B8C
12-13 10:43:32.559 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002add-0000-1000-8000-00805f9b34fb
12-13 10:43:32.559 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=98:12:88:77:00:15 UUID=00002add-0000-1000-8000-00805f9b34fb Status=0
12-13 10:43:32.569 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x400C2793473B679886FCB04510E4CDCBA38C2B8C
12-13 10:43:32.569 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0xC06A44
12-13 10:43:32.569 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002add-0000-1000-8000-00805f9b34fb
12-13 10:43:32.569 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=98:12:88:77:00:15 UUID=00002add-0000-1000-8000-00805f9b34fb Status=0
12-13 10:43:32.569 7621-7643/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0xC06A44
12-13 10:43:32.569 7621-7643/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Network pdu sent: 0x000C2793473B679886FCB04510E4CDCBA38C2B8C6A44
12-13 10:43:32.569 7621-7643/no.nordicsemi.android.nrfmeshprovisioner V/MeshMessageHandler: Switching current state on write complete ConfigCompositionDataGet to ConfigCompositionDataStatus
12-13 10:43:32.639 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:32.639 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0x400C3BF3E4D5D32B6611C9A0430168E45E013C5C
12-13 10:43:32.679 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:32.679 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0xC08528CB43E9BF1DECC4B0
12-13 10:43:32.679 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Received network pdu: 0x000C3BF3E4D5D32B6611C9A0430168E45E013C5C8528CB43E9BF1DECC4B0
12-13 10:43:32.689 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Privacy Random: 0000000000000000006611C9A0430168
    TTL for received message: 10
    Sequence number of received access message: 0
    Received a segmented access message from: 002B
12-13 10:43:32.689 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: SEG O: 0
    SEG N: 2
    Current SeqAuth value 0
    Starting incomplete timer for src: 002B
12-13 10:43:32.689 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataStatus: Message reassembly may not be complete yet
12-13 10:43:32.729 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:32.729 7621-7643/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0x400CF46E0F9988AE184FC6819A528C1C3FFCB0DD
12-13 10:43:32.729 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:32.729 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0xC04891656D545D56BD8856
12-13 10:43:32.729 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Received network pdu: 0x000CF46E0F9988AE184FC6819A528C1C3FFCB0DD4891656D545D56BD8856
12-13 10:43:32.729 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Privacy Random: 000000000000000000184FC6819A528C
    TTL for received message: 10
12-13 10:43:32.739 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Sequence number of received access message: 1
    Received a segmented access message from: 002B
12-13 10:43:32.739 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: SEG O: 1
    SEG N: 2
    Last SeqAuth value 0
    Current SeqAuth value 0
    Restarting incomplete timer for src: 002B
12-13 10:43:32.739 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataStatus: Message reassembly may not be complete yet
12-13 10:43:33.319 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:33.319 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0x400C10883D6EBB5B3F4C1D3EA3CE81ADACFA6F43
12-13 10:43:33.339 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: All segments received cancelling incomplete timer
    Block acknowledgement payload: 000000000003
    Creating unsegmented transport control
    Unsegmented Lower transport control PDU 00000000000003
12-13 10:43:33.339 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Encryption key: 09D98362AFD9980568560D7ABB90472E
    Privacy key: F9CA93F9110E9AD5EF741B35DF2C35F4
    Sequence Number: 00007C
    Network nonce: 008A00007C07FF000000000000
12-13 10:43:33.349 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Encrypted Network payload: DC0AA0F80619B685C5A0F183133F75AD7E
12-13 10:43:33.349 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataStatus: Sending acknowledgement: 000CA3485591C16DDC0AA0F80619B685C5A0F183133F75AD7E
12-13 10:43:33.349 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0x400CA3485591C16DDC0AA0F80619B685C5A0F183
12-13 10:43:33.349 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002add-0000-1000-8000-00805f9b34fb
12-13 10:43:33.349 7621-7643/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=98:12:88:77:00:15 UUID=00002add-0000-1000-8000-00805f9b34fb Status=0
12-13 10:43:33.349 7621-7643/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0x400CA3485591C16DDC0AA0F80619B685C5A0F183
12-13 10:43:33.359 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Sending data : 0xC0133F75AD7E
12-13 10:43:33.359 7621-7621/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: writeCharacteristic() - uuid: 00002add-0000-1000-8000-00805f9b34fb
12-13 10:43:33.359 7621-7645/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onCharacteristicWrite() - Device=98:12:88:77:00:15 UUID=00002add-0000-1000-8000-00805f9b34fb Status=0
12-13 10:43:33.369 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Data written: 0xC0133F75AD7E
12-13 10:43:33.369 7621-7645/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Network pdu sent: 0x000CA3485591C16DDC0AA0F80619B685C5A0F183133F75AD7E
12-13 10:43:33.369 7621-7696/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onNotify() - Device=98:12:88:77:00:15 UUID=00002ade-0000-1000-8000-00805f9b34fb
12-13 10:43:33.369 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/BleMeshManager: Characteristic notified: 0xC0533AD77F
12-13 10:43:33.369 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/MeshManagerApi: Received network pdu: 0x000C10883D6EBB5B3F4C1D3EA3CE81ADACFA6F43533AD77F
12-13 10:43:33.369 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Privacy Random: 0000000000000000003F4C1D3EA3CE81
    TTL for received message: 10
    Sequence number of received access message: 2
12-13 10:43:33.379 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/NetworkLayer: Received a segmented access message from: 002B
12-13 10:43:33.379 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: SEG O: 2
    SEG N: 2
    Last SeqAuth value 0
    Current SeqAuth value 0
    Restarting incomplete timer for src: 002B
12-13 10:43:33.379 7621-7621/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: Block ack value: 3
12-13 10:43:33.379 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/LowerTransportLayer: Restarting block acknowledgement timer for src: 002B
    All segments received
    Block ack sent? true
12-13 10:43:33.389 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/AccessLayer: Opcode length: 1 Octets
    Received Access PDU 02000C001A000100080003000001020000000010000101000010
12-13 10:43:33.389 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataStatus: Received composition data status
    Company identifier: 000C
    Product identifier: 001A
    Version identifier: 0001
    crpl: 0008
    Features: 0003
    Relay feature: true
    Proxy feature: true
    Friend feature: false
    Low power feature: false
    Location identifier: 0100
12-13 10:43:33.399 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/ConfigCompositionDataStatus: Number of sig models: 2
    Number of vendor models: 0
    Sig model ID 0 : 0000
    Sig model ID 1 : 1000
    Location identifier: 0100
    Number of sig models: 1
    Number of vendor models: 0
    Sig model ID 0 : 1000
    Number of elements: 2
12-13 10:43:33.419 7621-7696/no.nordicsemi.android.nrfmeshprovisioner V/MeshMessageHandler: Switched to No operation state`

`12-13 10:43:34.029 7621-7621/no.nordicsemi.android.nrfmeshprovisioner W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41742d58)
12-13 10:43:34.049 7621-7621/no.nordicsemi.android.nrfmeshprovisioner W/System.err: java.lang.NullPointerException
        at no.nordicsemi.android.meshprovisioner.transport.LowerTransportLayer.sendBlockAck(LowerTransportLayer.java:686)
        at no.nordicsemi.android.meshprovisioner.transport.LowerTransportLayer.lambda$initSegmentedAccessAcknowledgementTimer$0$LowerTransportLayer(LowerTransportLayer.java:655)
        at no.nordicsemi.android.meshprovisioner.transport.LowerTransportLayer$$Lambda$0.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5052)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
12-13 10:43:34.059 7621-7621/no.nordicsemi.android.nrfmeshprovisioner W/System.err:     at dalvik.system.NativeStart.main(Native Method)`

**Comment by WangManAndroid** [comment]
It may appear on some Android phones

**Comment by roshanrajaratnam** [comment]
@WangManAndroid Is it possible to provide more details on this? This is something I haven't seen and have you made any changes?

Also the library have moved on from using the version 1.0.4 library and the latest dev branch contains a lot of the new improvements and bug fixes. I highly recommend to switch to the newer version as it has fixed a lot of the internals in the library.

**Comment by roshanrajaratnam** [comment]
Closing this due to inactivity. Please feel free to reopen!
