### ISSUE TITLE
Null Pointer Exception : InternalTransportCallbacks.onMeshPduCreated

### ISSUE THREAD

**Issue by Mavericksb** [NordicSemiconductor/Android-nRF-Mesh-Library#403]
---
Hello,
during Provisioning phase we experienced occasional crashes.

Here you can find the stacktrace log :

**StackTrace
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void no.nordicsemi.android.meshprovisioner.InternalTransportCallbacks.onMeshPduCreated(int, byte[])' on a null object reference
       at no.nordicsemi.android.meshprovisioner.transport.MeshMessageState.sendSegmentAcknowledgementMessage(MeshMessageState.java:146)
       at no.nordicsemi.android.meshprovisioner.transport.LowerTransportLayer.sendBlockAck(LowerTransportLayer.java:756)
       at no.nordicsemi.android.meshprovisioner.transport.LowerTransportLayer.lambda$initSegmentedAccessAcknowledgementTimer$0$LowerTransportLayer(LowerTransportLayer.java:704)
       at no.nordicsemi.android.meshprovisioner.transport.-$$Lambda$LowerTransportLayer$OqXRgSPSKQR6i6Ap1Fez71k04mA.run(:12)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6815)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Platform details:**
 - OS: Android
 - Nordic Library Version  : 
implementation 'no.nordicsemi.android.support.v18:scanner:1.4.3'
implementation 'no.nordicsemi.android:ble:2.1.1'
implementation 'no.nordicsemi.android:dfu:1.9.0'

**Comment by roshanrajaratnam** [comment]
Hi what's the mesh library version you are using and have you made any changes to the internals?

**Comment by Eklow02** [comment]
Hi, I get the same error with version 3.1.6

It looks like the error occurs when I try to send several messages in quick succession.
