### ISSUE TITLE
Version 2.4.4 app crashes

### ISSUE THREAD

**Issue by xhtlxa** [NordicSemiconductor/Android-nRF-Mesh-Library#429]
When the data received by the app is divided into frames (greater than 11 bytes), the program will crash。
Below is the error log：

java.lang.NullPointerException: Attempt to invoke virtual method 'int no.nordicsemi.android.mesh.transport.Message.getTtl()' on a null object reference
        at no.nordicsemi.android.mesh.transport.MeshMessageState.getTtl(MeshMessageState.java:138)
        at no.nordicsemi.android.mesh.transport.LowerTransportLayer.parseSegmentedAccessLowerTransportPDU(LowerTransportLayer.java:449)
        at no.nordicsemi.android.mesh.transport.NetworkLayer.parseAccessMessage(NetworkLayer.java:319)
        at no.nordicsemi.android.mesh.transport.NetworkLayer.parseMeshMessage(NetworkLayer.java:268)
        at no.nordicsemi.android.mesh.transport.DefaultNoOperationMessageState.parseMeshPdu(DefaultNoOperationMessageState.java:60)
        at no.nordicsemi.android.mesh.transport.BaseMeshMessageHandler.parseMeshPduNotifications(BaseMeshMessageHandler.java:147)
        at no.nordicsemi.android.mesh.MeshMessageHandler.parseMeshPduNotifications(MeshMessageHandler.java:61)
        at no.nordicsemi.android.mesh.MeshManagerApi.parseNotifications(MeshManagerApi.java:304)
        at no.nordicsemi.android.mesh.MeshManagerApi.handleNotifications(MeshManagerApi.java:276)
        at no.nordicsemi.android.nrfmesh.viewmodels.NrfMeshRepository.onDataReceived(NrfMeshRepository.java:481)
        at no.nordicsemi.android.nrfmesh.ble.BleMeshManager$1.lambda$initialize$0(BleMeshManager.java:119)

**Comment by Nuclear6** [comment]
can you show capture air packet data?
