### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by luoqii** [NordicSemiconductor/Android-nRF-Mesh-Library#43]
08-22 15:31:10.601 10887-10887/no.nordicsemi.android.nrfmeshprovisioner V/ScannerFragment: scan started
08-22 15:31:10.608 10887-10887/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothAdapter: isLeEnabled(): ON
08-22 15:31:10.613 10887-22242/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=7 mScannerId=0
08-22 15:31:10.649 10887-10901/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: close()
    unregisterApp() - mClientIf=8
08-22 15:31:10.699 10887-10925/no.nordicsemi.android.nrfmeshprovisioner D/OpenGLRenderer: endAllActiveAnimators on 0x779be4a000 (RippleDrawable) with handle 0x779b2582a0
08-22 15:31:15.808 10887-10887/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: connect() - device: 9E:16:11:07:DA:78, auto: false
    registerApp()
08-22 15:31:15.809 10887-10887/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: registerApp() - UUID=252eef3f-9b0c-4b1b-a048-0e3544d1df75
08-22 15:31:15.810 10887-10901/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onClientRegistered() - status=0 clientIf=8
08-22 15:31:16.216 10887-10887/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothAdapter: isLeEnabled(): ON
08-22 15:31:16.221 10887-10887/no.nordicsemi.android.nrfmeshprovisioner V/ScannerFragment: stopping scan
08-22 15:31:16.519 10887-10926/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=8 device=9E:16:11:07:DA:78
08-22 15:31:16.583 10887-10887/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: discoverServices() - device: 9E:16:11:07:DA:78
08-22 15:31:16.957 10887-10902/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onConnectionUpdated() - Device=9E:16:11:07:DA:78 interval=6 latency=0 timeout=500 status=0
08-22 15:31:17.343 10887-22242/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onSearchComplete() = Device=9E:16:11:07:DA:78 Status=0
08-22 15:31:17.538 10887-22242/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: setCharacteristicNotification() - uuid: 00002ade-0000-1000-8000-00805f9b34fb enable: true
08-22 15:31:17.571 10887-22242/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onConnectionUpdated() - Device=9E:16:11:07:DA:78 interval=39 latency=0 timeout=500 status=0
08-22 15:31:17.715 10887-10901/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: configureMTU() - device: 9E:16:11:07:DA:78 mtu: 517
08-22 15:31:17.782 10887-10926/no.nordicsemi.android.nrfmeshprovisioner D/BluetoothGatt: onConfigureMTU() - Device=9E:16:11:07:DA:78 mtu=158 status=0
08-22 15:31:17.803 10887-10926/no.nordicsemi.android.nrfmeshprovisioner W/BluetoothGatt: Unhandled exception in callback
    java.lang.NullPointerException: Attempt to invoke virtual method 'void no.nordicsemi.android.meshprovisioner.configuration.ProvisionedMeshNode.setBluetoothDeviceAddress(java.lang.String)' on a null object reference
        at no.nordicsemi.android.nrfmeshprovisioner.service.MeshService.onDeviceReady(MeshService.java:358)
        at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onDeviceReady(BleManager.java:1053)
        at no.nordicsemi.android.nrfmeshprovisioner.ble.BleMeshManager$1.onDeviceReady(BleMeshManager.java:179)
        at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.nextRequest(BleManager.java:1513)
        at no.nordicsemi.android.ble.BleManager$BleManagerGattCallback.onMtuChanged(BleManager.java:1459)
        at android.bluetooth.BluetoothGatt$1$13.run(BluetoothGatt.java:610)
        at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:725)
        at android.bluetooth.BluetoothGatt.-wrap0(Unknown Source:0)
        at android.bluetooth.BluetoothGatt$1.onConfigureMTU(BluetoothGatt.java:605)
        at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:208)
        at android.os.Binder.execTransact(Binder.java:697)

**Comment by luoqii** [comment]
device service list is incorrect.
