### ISSUE TITLE
Unknown pattern character 'X'

### ISSUE THREAD

**Issue by DevHachi** [NordicSemiconductor/Android-nRF-Mesh-Library#433]
---

**Describe the bug**
When trying to load the mesh beacon data the app crashes when trying to get mesh beacon data from scan record.

**To Reproduce**
Open App once. Close App and open it again.
Or: Scan for device, read meshBeaconData from scan Record.
Both ways do lead to an crash.

**Expected behavior**
should not crash.

**Platform details:**
 - Device: Huawei P8
 - OS: Android 6.0
 - Library Version: 3.1.5

**Logs / Screenshots**
```java.lang.ExceptionInInitializerError
        at no.nordicsemi.android.mesh.MeshManagerApi.isMeshBeacon(MeshManagerApi.java:651)
        at no.nordicsemi.android.mesh.MeshManagerApi.getMeshBeaconData(MeshManagerApi.java:666)
        at com.quimron.ble_mesh.BleMesh.identifyNode(BleMesh.kt:275)
        at com.quimron.ble_mesh.BleMesh.access$identifyNode(BleMesh.kt:27)
        at com.quimron.ble_mesh.BleMesh$addDeviceToMesh$2$1.invoke(BleMesh.kt:188)
        at com.quimron.ble_mesh.BleMesh$addDeviceToMesh$2$1.invoke(BleMesh.kt:187)
        at com.quimron.ble_mesh.BleMesh.connectToDevice$lambda-26$lambda-25(BleMesh.kt:367)
        at com.quimron.ble_mesh.BleMesh.lambda$NcKof_1TOBSGM-QidILhLgmLnZg(BleMesh.kt)
        at com.quimron.ble_mesh.-$$Lambda$BleMesh$NcKof_1TOBSGM-QidILhLgmLnZg.onRequestCompleted(lambda)
        at no.nordicsemi.android.ble.Request.lambda$notifySuccess$1$Request(Request.java:1203)
        at no.nordicsemi.android.ble.-$$Lambda$Request$ep6TD_94xCe5LaEafH2PrarR3yc.run(lambda)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)
        at android.app.ActivityThread.main(ActivityThread.java:5546)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
     Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at no.nordicsemi.android.mesh.utils.MeshParserUtils.<clinit>(MeshParserUtils.java:47)
        at no.nordicsemi.android.mesh.MeshManagerApi.isMeshBeacon(MeshManagerApi.java:651) 
        at no.nordicsemi.android.mesh.MeshManagerApi.getMeshBeaconData(MeshManagerApi.java:666) 
        at com.quimron.ble_mesh.BleMesh.identifyNode(BleMesh.kt:275) 
        at com.quimron.ble_mesh.BleMesh.access$identifyNode(BleMesh.kt:27) 
        at com.quimron.ble_mesh.BleMesh$addDeviceToMesh$2$1.invoke(BleMesh.kt:188) 
        at com.quimron.ble_mesh.BleMesh$addDeviceToMesh$2$1.invoke(BleMesh.kt:187) 
        at com.quimron.ble_mesh.BleMesh.connectToDevice$lambda-26$lambda-25(BleMesh.kt:367) 
        at com.quimron.ble_mesh.BleMesh.lambda$NcKof_1TOBSGM-QidILhLgmLnZg(BleMesh.kt) 
        at com.quimron.ble_mesh.-$$Lambda$BleMesh$NcKof_1TOBSGM-QidILhLgmLnZg.onRequestCompleted(lambda) 
        at no.nordicsemi.android.ble.Request.lambda$notifySuccess$1$Request(Request.java:1203) 
        at no.nordicsemi.android.ble.-$$Lambda$Request$ep6TD_94xCe5LaEafH2PrarR3yc.run(lambda) 
        at android.os.Handler.handleCallback(Handler.java:743) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:150) 
        at android.app.ActivityThread.main(ActivityThread.java:5546) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) ```

```java.lang.ExceptionInInitializerError
        at no.nordicsemi.android.mesh.Provisioner.setGlobalTtl(Provisioner.java:298)
        at no.nordicsemi.android.mesh.data.ProvisionersDao_Impl.getProvisioners(ProvisionersDao_Impl.java:278)
        at no.nordicsemi.android.mesh.MeshNetworkDb.lambda$loadNetwork$1(MeshNetworkDb.java:178)
        at no.nordicsemi.android.mesh.-$$Lambda$MeshNetworkDb$Lx_nOticRyYIhf1gJ5NjtiyshXQ.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:833)
     Caused by: java.lang.IllegalArgumentException: Unknown pattern character 'X'
        at java.text.SimpleDateFormat.validatePatternCharacter(SimpleDateFormat.java:323)
        at java.text.SimpleDateFormat.validatePattern(SimpleDateFormat.java:312)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:365)
        at no.nordicsemi.android.mesh.utils.MeshParserUtils.<clinit>(MeshParserUtils.java:47)
        at no.nordicsemi.android.mesh.Provisioner.setGlobalTtl(Provisioner.java:298) 
        at no.nordicsemi.android.mesh.data.ProvisionersDao_Impl.getProvisioners(ProvisionersDao_Impl.java:278) 
        at no.nordicsemi.android.mesh.MeshNetworkDb.lambda$loadNetwork$1(MeshNetworkDb.java:178) 
        at no.nordicsemi.android.mesh.-$$Lambda$MeshNetworkDb$Lx_nOticRyYIhf1gJ5NjtiyshXQ.run(lambda) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:833) ```

**Comment by roshanrajaratnam** [comment]
Thanks for reporting and this should be caught in the app.

**Comment by roshanrajaratnam** [comment]
Hi what firmware are you using to test this?

**Comment by DevHachi** [comment]
You mean the firmware of the lights?
If so I can't tell you because I don't know. Those are Toran lights.

**Comment by DevHachi** [comment]
From my perspective it seems like this is the culprit:
`private static final SimpleDateFormat SDF = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX", Locale.US);`
Because 'X' is not supported on devices before nougat, which an android 6 device definitely is.

**Comment by roshanrajaratnam** [comment]
this is indeed hte culprit. I will push a fix later today

**Comment by roshanrajaratnam** [comment]
@DevHachi check this please. the last fix introduced a timestamp parsing issue however now is handled properly and maintains compatibility between both Android and iOS.
