### ISSUE TITLE
Crash while setting subscribe

### ISSUE THREAD

**Issue by Rawa** [NordicSemiconductor/Android-nRF-Mesh-Library#540]
---

**Describe the bug**
Crash while doing a subscribe to a group on a node.

**To Reproduce**
I'm, not exactly sure how to reproduce. But seems like it happens after i loaded another mesh (or the same) into my meshManagerApi. Basically I call, importMeshNetworkJson, then when using a mesh and receiving back a configuration message I get this internal crash.

The message is successfully sent away and I will see the change applied to the mesh, but the parsing of the status returned seems to fail.

**Platform details:**
 - Device: Pixel 6 Pro
 - OS: 13
 - Library Version (or Commit): 3.2.4

**Logs / Screenshots**
Crash is on this line because of message being null: https://github.com/NordicSemiconductor/Android-nRF-Mesh-Library/blob/2ef8d19b278ae311802924bb76fe50eb031423bd/mesh/src/main/java/no/nordicsemi/android/mesh/transport/DefaultNoOperationMessageState.java#L531
```
2022-09-22 10:00:34.319 6769-6869/com.tyrilights.intellilight.debug E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-10
    Process: com.tyrilights.intellilight.debug, PID: 6769
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.util.SparseArray no.nordicsemi.android.mesh.transport.Message.getNetworkLayerPdu()' on a null object reference
        at no.nordicsemi.android.mesh.transport.DefaultNoOperationMessageState.parseControlMessage(DefaultNoOperationMessageState.java:523)
        at no.nordicsemi.android.mesh.transport.DefaultNoOperationMessageState.parseMeshPdu(DefaultNoOperationMessageState.java:78)
        at no.nordicsemi.android.mesh.transport.BaseMeshMessageHandler.parseMeshPduNotifications(BaseMeshMessageHandler.java:156)
        at no.nordicsemi.android.mesh.MeshMessageHandler.parseMeshPduNotifications(MeshMessageHandler.java:61)
        at no.nordicsemi.android.mesh.MeshManagerApi.parseNotifications(MeshManagerApi.java:280)
        at no.nordicsemi.android.mesh.MeshManagerApi.handleNotifications(MeshManagerApi.java:252)
        at com.technocreatives.beckon.mesh.BeckonMeshManagerApi$handleNotifications$1$3.emit(BeckonMeshManagerApi.kt:174)
        at com.technocreatives.beckon.mesh.BeckonMeshManagerApi$handleNotifications$1$3.emit(BeckonMeshManagerApi.kt:172)
        at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.emit(Emitters.kt:224)
        at com.technocreatives.beckon.extensions.BeckonDeviceKt$changes$$inlined$map$1$2.emit(Emitters.kt:224)
        at com.technocreatives.beckon.extensions.BeckonDeviceKt$changes$$inlined$filter$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.DistinctFlowImpl$collect$2.emit(Distinct.kt:81)
        at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
        at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e33bdba, Dispatchers.IO]
```

**Comment by Rawa** [comment]
Believe this is an issue on my side and accidentally having two instances of MeshManagerApi, gonna look into a bit more to confirm this is not a issue for the library.

**Comment by Rawa** [comment]
Going to close this issue, I believe it occured because we had an old instance still receiving some data and thus not managing state correctly.
