### ISSUE TITLE
Attempt to invoke virtual method 'int  no.nordicsemi.android.mesh.transport.ProvisionedMeshNode.incrementSequenceNumber()' on a null object reference

### ISSUE THREAD

**Issue by Pallav-sculptsoft** [NordicSemiconductor/Android-nRF-Mesh-Library#560]
**Logs**
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'int no.nordicsemi.android.mesh.transport.ProvisionedMeshNode.incrementSequenceNumber()' on a null object reference
[mono-rt]   at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00068] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/JniEnvironment.g.cs:11884 
[mono-rt]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00030] in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:66 
[mono-rt]   at NO.Nordicsemi.Android.Mesh.MeshManagerApi.CreateMeshPdu (System.Int32 dst, NO.Nordicsemi.Android.Mesh.Transport.MeshMessage meshMessage) [0x00046] in <c14f2183156e4cf882e2ea3baf99dd81>:0 
[mono-rt]   at BLE.Droid.BleManagerCallbacks+<>c.<OnDeviceReady>b__10_0 () [0x0001b] in /Users/sculptsoft/Downloads/BLE/BLE/BLE/BLE.Android/MainActivity.cs:382 
[mono-rt]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36 
[mono-rt]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-33/mcw/Java.Lang.IRunnable.cs:84 
[mono-rt]   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:22 
[mono-rt]   at (wrapper native-to-managed) Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(intptr,intptr)
[mono-rt]   --- End of managed Java.Lang.NullPointerException stack trace ---
[mono-rt] java.lang.NullPointerException: Attempt to invoke virtual method 'int no.nordicsemi.android.mesh.transport.ProvisionedMeshNode.incrementSequenceNumber()' on a null object reference
[mono-rt] 	at no.nordicsemi.android.mesh.transport.MeshTransport.createMeshMessage(MeshTransport.java:129)
[mono-rt] 	at no.nordicsemi.android.mesh.transport.ConfigMessageState.createAccessMessage(ConfigMessageState.java:76)
[mono-rt] 	at no.nordicsemi.android.mesh.transport.ConfigMessageState.<init>(ConfigMessageState.java:61)
[mono-rt] 	at no.nordicsemi.android.mesh.transport.BaseMeshMessageHandler.createConfigMeshMessage(BaseMeshMessageHandler.java:278)
[mono-rt] 	at no.nordicsemi.android.mesh.transport.BaseMeshMessageHandler.createMeshMessage(BaseMeshMessageHandler.java:244)
[mono-rt] 	at no.nordicsemi.android.mesh.MeshManagerApi.createMeshPdu(MeshManagerApi.java:897)
[mono-rt] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[mono-rt] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
[mono-rt] 	at android.os.Handler.handleCallback(Handler.java:883)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:100)
[mono-rt] 	at android.os.Looper.loop(Looper.java:224)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:7590)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Expected behavior**
wants to create successful pdu for mesh 

**Platform details:**
 - Device: Redmi Note 7S
 - OS: Android 10.0

**Comment by roshanrajaratnam** [comment]
Hi, are you still having trouble with this?
