### ISSUE TITLE
 FOREIGN KEY constraint failed on loading of default mesh network

### ISSUE THREAD

**Issue by mpiffari** [NordicSemiconductor/Android-nRF-Mesh-Library#593]
---
In my KMM app, which is consuming the Android-nRF-Mesh-Library, after reception of MeshManagerCallabacks
- onNetworkUpdated
- onNetworkLoaded 

NRF Mesh library is getting a fatal exception accessing the DB.
I'm getting this exception during the verify initial startup and intialization of mesh manager API.

---
**Platform details:**

implementation("androidx.sqlite:sqlite-bundled:2.5.0-alpha10")

---
**Logs / Screenshots**
Exception stack trace:
`2024-10-25 18:17:01.980 22885-22942 AndroidRuntime app E  FATAL EXCEPTION: 
pool-3-thread-2
Process: app, PID: 22885
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:961)
at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:790)
at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:89)
at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.android.kt:38)
at androidx.room.EntityInsertionAdapter.insertAndReturnId(EntityInsertionAdapter.android.kt:100)
at no.nordicsemi.android.mesh.data.ApplicationKeyDao_Impl.insert(ApplicationKeyDao_Impl.java:112)
at no.nordicsemi.android.mesh.MeshNetworkDb.lambda$insert$11(MeshNetworkDb.java:248)
at no.nordicsemi.android.mesh.MeshNetworkDb$$ExternalSyntheticLambda28.run(Unknown Source:4)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)`

**Comment by philips77** [comment]
Hi, let's wait for @roshanrajaratnam to come back.

Btw, you may check the database using Android Studio. Have a look at: https://developer.android.com/studio/inspect/database

**Comment by iDistrax** [comment]
@philips77 Awesome thank you. Looking forward to the Kotlin release.

**Comment by philips77** [comment]
Please forgive us delays caused by the vacation period.
We are focusing on the new library, but will try to keep the old one usable as well and fix bugs if necessary.
Regarding this issue, we need to wait until the main dev is back, sorry for the inconvienience.

**Comment by mpiffari** [comment]
Hi @iDistrax - @Fabbros,
did you manage to solve in some way this problem?

**Comment by Fabbros** [comment]
Unfortunately no.

But, luckily, our app stores a cloud backup of the mesh configuration so when someone encounters this problem, they just can uninstall+reinstall the app and download the backup again. It's a workaround.

**Comment by roshanrajaratnam** [comment]
@mpiffari Really sorry, I have noticed this until now. I have been busy with the kotlin library. Have you thought of migrating to the newest library?

I'm not entirely sure how I could reproduce this issue on my end.

**Comment by mpiffari** [comment]
@Fabbros 
In my case, I am storing a backup of the network database. How do you handle the seq_number? Do you store this parameter as well?
Mesh best practices state that seq_number is a runtime state rather than a configuration parameter, so it shouldn't be saved persistently. In your approach, does this mean you perform a fresh swap of the library database?

@roshanrajaratnam
I haven't planned a migration to the new library yet. Do you advise migrating now, or is support for this library no longer guaranteed?
Also, to reproduce the error (it doesn't happen every time, but it's worth testing), it seems necessary to run the import procedure.

**Comment by Fabbros** [comment]
> [@Fabbros](https://github.com/Fabbros) In my case, I am storing a backup of the network database. How do you handle the seq_number? Do you store this parameter as well? Mesh best practices state that seq_number is a runtime state rather than a configuration parameter, so it shouldn't be saved persistently. In your approach, does this mean you perform a fresh swap of the library database?

@mpiffari I update the provisioner's address whenever the backup is imported. It's a waste of address, but so far, in term of the use cases, it has been working. 
 
> [@roshanrajaratnam](https://github.com/roshanrajaratnam) I haven't planned a migration to the new library yet. Do you advise migrating now, or is support for this library no longer guaranteed? Also, to reproduce the error (it doesn't happen every time, but it's worth testing), it seems necessary to run the import procedure.

@mpiffari Same here. It isn't systematic tho, because after an uninstall+install procedure (of the app) it works, with the same backup.

**Comment by roshanrajaratnam** [comment]
@mpiffari I would recommend migrating to the kotlin library because we focus more on it right now.  If you have a particular CDB JSON could you share it with me so I can try importing to see how this could be reproduced?
